name: pet_adoption_app
description: "A beautiful app to find and adopt a new furry friend."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Networking & Caching
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  cached_network_image: ^3.3.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Navigation
  go_router: ^14.1.0

  # UI & UX
  photo_view: ^0.15.0
  confetti: ^0.7.0
  # flutter_staggered_grid_view: ^0.7.0 # For a more dynamic home screen layout
  # google_fonts: ^6.2.1 # For beautiful typography
  heroicons: ^0.11.0
  rxdart: ^0.27.7

  # Service Locator / Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.1

  # Models & Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter

# dependency_overrides:
# Force compatible versions for web builds
# web: 0.1.4-beta
# js: ^0.6.5

flutter:
  uses-material-design: true
