name: Deploy to GitHub Pages (Alternative)

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        cache: true
        
    - name: Flutter Doctor
      run: flutter doctor -v
        
    - name: Get Dependencies
      run: flutter pub get
      
    - name: Create API Keys (Demo)
      run: |
        mkdir -p lib/core/api
        cat << 'EOF' > lib/core/api/api_keys.dart
        // Demo API keys for GitHub Pages deployment
        const String theCatApiKey = 'demo_cat_api_key';
        const String theDogApiKey = 'demo_dog_api_key';
        EOF
        
    - name: Try Code Generation (Optional)
      run: |
        echo "Attempting code generation..."
        if flutter packages pub run build_runner build --delete-conflicting-outputs; then
          echo "Code generation successful"
        else
          echo "Code generation failed, continuing without it..."
        fi
      continue-on-error: true
        
    - name: Build Web
      run: |
        echo "Building web application..."
        flutter build web \
          --release \
          --web-renderer html \
          --base-href "/Pet_adoption_app/" \
          --dart-define=FLUTTER_WEB_USE_SKIA=false
          
    - name: Verify Build Output
      run: |
        echo "Checking build output..."
        ls -la build/web/
        echo "Index.html exists: $(test -f build/web/index.html && echo 'Yes' || echo 'No')"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy Pet Adoption App to GitHub Pages'
